### ISSUE TITLE
Navbar dashboard not working

### ISSUE THREAD

**Issue by 0xcabrex** [d4rckh/kab#1]
the "dashboard" navbar doesn't work
![Screenshot from 2020-10-13 22-53-31](https://user-images.githubusercontent.com/30289455/95894599-f1f48c00-0da6-11eb-91ff-979b16a5449e.png)

**Comment by andreiverse** [comment]
This is because the "a" element does not have a href prop

**Comment by andreiverse** [comment]
@0xcabrex Can you please check if it's fixed now on your side?

**Comment by 0xcabrex** [comment]
Yes, it works perfectly now.
Thanks for the fix!
