### ISSUE TITLE
Domain information on the sidebar not working

### ISSUE THREAD

**Issue by 0xcabrex** [d4rckh/kab#2]
The "Domain Information" on the navbar does not work, `/setupdomain` does not exist

**Comment by andreiverse** [comment]
Looks like the "a" has the wrong href value.

**Comment by andreiverse** [comment]
Should be fixed on main branch, @0xcabrex check if it's still not working

**Comment by 0xcabrex** [comment]
The Domain Information tab works fine from my side
Thanks for the fix!
