### ISSUE TITLE
Tutorials do not work

### ISSUE THREAD

**Issue by 0xcabrex** [d4rckh/kab#4]
The getting started, Learning and Customising tabs do not seem to work yet

![Screenshot from 2020-10-13 22-58-53](https://user-images.githubusercontent.com/30289455/95895533-70056280-0da8-11eb-8125-45629c6e6c81.png)

**Comment by andreiverse** [comment]
#3 same reason as this one

**Comment by 0xcabrex** [comment]
Now they do work!
